[tox]
envlist = py, codestyle
skipsdist = True

[testenv]
deps =
    pytest
    jsonpickle>=3.0.0
    sqlalchemy>=2.0.0
    errbot
commands = pytest -v

[testenv:codestyle]
deps =
    ruff
    isort
commands =
    ruff check sql.py test_sql.py
    ruff format --check sql.py test_sql.py
    isort --check-only sql.py test_sql.py
